# Version: 2025.4.1
geox-url:
  geoip: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat'
  geosite: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat'
  mmdb: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb'
  asn: 'https://geodata.kelee.one/GeoLite2-ASN-P3TERX.mmdb'
geo-auto-update: true
geo-update-interval: 128
unified-delay: true
tcp-concurrent: true
tun:
  enable: true
  stack: system
  dns-hijack:
    - 0.0.0.0:53
dns:
  enable: true
  listen: 0.0.0.0:53
  default-nameserver:
    - tcp://223.5.5.5:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - rule-set:Fakeip-Filter
    - '*.lan'
    - '*.direct'
    - 'xbox.*.microsoft.com'
    - 'stun.*'
    - 'localhost.*.qq.com'
    - 'localhost.*.weixin.qq.com'
    - 'ntp.*.com'
    - 'time.*.com'
    - 'ntp?.*.com'
    - 'time?.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'PDC._msDCS.*.*'
    - 'DC._msDCS.*.*'
    - 'GC._msDCS.*.*'
  fake-ip-filter-mode: blacklist
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - 'https://1.0.0.1/dns-query#全球加速'
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 240.0.0.0/4
  nameserver-policy:
    'api-huacloud.net': ['https://223.5.5.5/dns-query','https://1.12.12.12/dns-query']
    'checkipv6.dyndns.com': ['https://223.5.5.5/dns-query','https://1.12.12.12/dns-query']
    'rule-set:WeChat': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:GoogleFCM': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:Apple': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:Bing': 'https://1.0.0.1/dns-query#全球加速'
    'rule-set:Streaming': 'https://1.0.0.1/dns-query#国际媒体'
    'geosite:cn': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
proxy-groups:
  - name: 全球加速
    type: select
    proxies:
      - Fallback
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 下载节点
      - 其它节点
      - DIRECT
  - name: 国际媒体
    type: select
    proxies:
      - 全球加速
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: 游戏下载
    type: select
    proxies:
      - DIRECT
      - 下载节点
      - 全球加速
      - 其它节点
  - name: 游戏加速
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 下载节点
      - 其它节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
  - name: Microsoft
    type: select
    proxies:
      - 全球加速
      - DIRECT
      - 其它节点
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 其它节点
  - name: OneDrive
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 下载节点
  - name: 其它节点
    type: select
    filter: '(?=.*())^((?!(Netea|香港|新加|狮城|日本|Exp|Tra|台湾|美国)).)*$'
    use:
      - VPN
  - name: Fallback
    type: fallback
    proxies:
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 下载节点
    type: url-test
    filter: '实验'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 香港节点
    type: url-test
    filter: '港|HK|(?i)Hong'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 台湾节点
    type: url-test
    filter: '台|TW|(?i)Taiwan'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 日本节点
    type: url-test
    filter: '日|JP|(?i)Japan'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 新加坡节点
    type: url-test
    filter: '新加|狮|獅|SG|(?i)Singapore'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 美国节点
    type: url-test
    filter: '美|US|(?i)States|American'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
proxy-providers:
  VPN:
    type: http
    url: 'URL'
    interval: 6400
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 600
      url: 'http://www.gstatic.com/generate_204'
rule-providers:
  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/Openwrt-Clash.meta/main/Rules/ProxyMedia.yaml'
    interval: 86400
  GoogleFCM:
    type: http
    behavior: classical
    path: ./rule_provider/GoogleFCM.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml'
    interval: 86400
  Google:
    type: http
    behavior: classical
    path: ./rule_provider/Google.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml'
    interval: 86400
  Apple:
    type: http
    behavior: classical
    path: ./rule_provider/Apple.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml'
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./rule_provider/Microsoft.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml'
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    path: ./rule_provider/OneDrive.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml'
    interval: 86400
  Bing:
    type: http
    behavior: classical
    path: ./rule_provider/Bing.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml'
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    path: ./rule_provider/GameDownload.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GameDownload.yaml'
    interval: 86400
  GameDownloadCN:
    type: http
    behavior: classical
    path: ./rule_provider/GameDownloadCN.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/Openwrt-Clash.meta/main/Rules/GameDownloadCN.yaml'
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: ./rule_provider/Game.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml'
    interval: 86400
  Steam:
    type: http
    behavior: classical
    path: ./rule_provider/Steam.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/Openwrt-Clash.meta/main/Rules/Game.yaml'
    interval: 86400
  WeChat:
    type: http
    behavior: classical
    path: ./rule_provider/WeChat.yaml
    url: 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/WeChat/WeChat.yaml'
    interval: 86400
  HTTPDNS:
    type: http
    behavior: classical
    path: ./rule_provider/HTTPDNS.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.yaml'
    interval: 86400
  GlobalDirect:
    type: http
    behavior: classical
    path: ./rule_provider/GlobalDirect.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/Openwrt-Clash.meta/main/Rules/GlobalDirect.yaml'
    interval: 86400
  Fakeip-Filter:
    type: http
    behavior: classical
    path: ./rule_provider/Fakeip-Filter.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/Openwrt-Clash.meta/main/Rules/fakeip-filter.yaml'
    interval: 86400
  LAN:
    type: http
    behavior: classical
    path: ./rule_provider/Lan.yaml
    url: 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Lan/Lan.yaml'
    interval: 86400
rules:
  - RULE-SET,LAN,DIRECT,no-resolve
  - RULE-SET,GlobalDirect,DIRECT,no-resolve
  - RULE-SET,HTTPDNS,REJECT,no-resolve
  - RULE-SET,Streaming,国际媒体,no-resolve
  - RULE-SET,GoogleFCM,DIRECT,no-resolve
  - GEOIP,telegram,Fallback,no-resolve
  - GEOSITE,telegram,Fallback
  - RULE-SET,OneDrive,OneDrive,no-resolve
  - RULE-SET,Steam,全球加速,no-resolve
  - RULE-SET,Microsoft,Microsoft,no-resolve
  - RULE-SET,Apple,Apple,no-resolve
  - RULE-SET,Google,全球加速,no-resolve
  - RULE-SET,WeChat,DIRECT,no-resolve
  - RULE-SET,GameDownloadCN,DIRECT,no-resolve
  - DOMAIN-SUFFIX,recaptcha.net,全球加速
  - RULE-SET,GameDownload,游戏下载,no-resolve
  - RULE-SET,Game,游戏加速,no-resolve
  - GEOSITE,gfw,全球加速
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,全球加速