# Version: 2025.2.0 dev
geox-url:
  geoip: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat'
  geosite: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat'
  mmdb: 'https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb'
geo-auto-update: true
geo-update-interval: 167
unified-delay: true
tcp-concurrent: true
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - 0.0.0.0:53
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - tcp://223.5.5.5:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - rule-set:Fakeip-Filter
    - '*.lan'
    - '*.direct'
    - 'xbox.*.microsoft.com'
    - 'stun.*'
    - 'localhost.*.qq.com'
    - 'localhost.*.weixin.qq.com'
    - 'ntp.*.com'
    - 'time.*.com'
    - 'ntp?.*.com'
    - 'time?.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'PDC._msDCS.*.*'
    - 'DC._msDCS.*.*'
    - 'GC._msDCS.*.*'
  fake-ip-filter-mode: blacklist
  nameserver:
    - https://doh-pure.onedns.net/dns-query
    - https://doh.pub/dns-query
  fallback:
    - 'tls://1.1.1.1:853#全球加速'
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 240.0.0.0/4
    domain:
      - '+.bing.com'
      - '+.bing.cn'
  nameserver-policy:
    'geosite:Bing': 'tls://1.1.1.1:853#全球加速'
    'geosite:bahamut': 'tls://1.1.1.1:853#国际媒体'
    'geosite:geolocation-!cn': 'tls://1.1.1.1:853#全球加速'
    'geosite:cn': ['https://doh-pure.onedns.net/dns-query', 'https://doh.pub/dns-query']
proxy-groups:
  - name: 全球加速
    type: select
    proxies:
      - Fallback
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 下载节点
      - 其它节点
      - DIRECT
  - name: 国际媒体
    type: select
    proxies:
      - 全球加速
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: 游戏加速
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 下载节点
      - 其它节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
  - name: Microsoft
    type: select
    proxies:
      - 全球加速
      - DIRECT
      - 其它节点
  - name: OneDrive
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 下载节点
  - name: 其它节点
    type: select
    filter: '(?=.*())^((?!(Netea|香港|新加|狮城|日本|Exp|Tra|台湾|美国)).)*$'
    use:
      - VPN
  - name: Fallback
    type: fallback
    proxies:
      - 日本节点
      - 新加坡节点
      - 香港节点
      - 台湾节点
      - 美国节点
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 下载节点
    type: url-test
    filter: '实验'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 香港节点
    type: url-test
    filter: '港|HK|(?i)Hong'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 台湾节点
    type: url-test
    filter: '台|TW|(?i)Taiwan'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 日本节点
    type: url-test
    filter: '日|JP|(?i)Japan'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 新加坡节点
    type: url-test
    filter: '新加|狮|獅|SG|(?i)Singapore'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
  - name: 美国节点
    type: url-test
    filter: '美|US|(?i)States|American'
    use:
      - VPN
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
proxy-providers:
  VPN:
    type: http
    url: 'URL'
    interval: 3600
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 600
      url: 'http://www.gstatic.com/generate_204'
rule-providers:
  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml'
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: ./rule_provider/Game.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/ProxyConfig-Clash.meta/main/Rules/Game.yaml'
    interval: 86400
  HTTPDNS:
    type: http
    behavior: classical
    path: ./rule_provider/HTTPDNS.yaml
    url: 'https://raw.githubusercontent.com/VirgilClyne/GetSomeFries/main/ruleset/HTTPDNS.Block.yaml'
    interval: 86400
  Fakeip-Filter:
    type: http
    behavior: classical
    path: ./rule_provider/Fakeip-Filter.yaml
    url: 'https://raw.githubusercontent.com/Toyro7356/ProxyConfig-Clash.meta/main/Rules/fakeip-filter.yaml'
    interval: 86400
rules:
  - SRC-PORT,31286,DIRECT
  - RULE-SET,HTTPDNS,REJECT,no-resolve
  - DOMAIN-SUFFIX,onedns.net,DIRECT,no-resolve
  - DOMAIN-SUFFIX,doh.pub,DIRECT,no-resolve
  - DOMAIN-SUFFIX,sc.com,DIRECT,no-resolve
  - GEOIP,google,全球加速,no-resolve
  - GEOSITE,google,全球加速,no-resolve
  - GEOSITE,category-games@cn,DIRECT,no-resolve
  - RULE-SET,Game,全球加速,no-resolve
  - GEOSITE,category-games,游戏加速,no-resolve
  - GEOIP,telegram,Fallback,no-resolve
  - GEOSITE,telegram,Fallback,no-resolve
  - GEOSITE,bahamut,台湾节点,no-resolve
  - GEOSITE,onedrive,OneDrive,no-resolve
  - GEOSITE,Bing,全球加速,no-resolve
  - GEOSITE,Microsoft,Microsoft,no-resolve
  - RULE-SET,Streaming,国际媒体,no-resolve
  - GEOSITE,gfw,全球加速,no-resolve
  - GEOSITE,cn,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,全球加速