# Version: 2025.6.1
proxy-providers:
  ProxyURL:
    type: http
    url: 'URL'
    interval: 6400
    path: ./ProxyURL.yaml
    health-check:
      enable: true
      interval: 600
      url: 'http://www.gstatic.com/generate_204'
unified-delay: true
tcp-concurrent: true
ipv6: true
tun:
  enable: true
  stack: system
  dns-hijack:
    - 0.0.0.0:53
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: true
  default-nameserver:
    - tcp://223.5.5.5:53
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - rule-set:Fakeip-Filter
    - '*.lan'
    - '*.direct'
    - 'xbox.*.microsoft.com'
    - 'stun.*'
    - 'localhost.*.qq.com'
    - 'localhost.*.weixin.qq.com'
    - 'ntp.*.com'
    - 'time.*.com'
    - 'ntp?.*.com'
    - 'time?.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - 'PDC._msDCS.*.*'
    - 'DC._msDCS.*.*'
    - 'GC._msDCS.*.*'
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  fallback:
    - 'https://1.0.0.1/dns-query#全球加速'
  direct-nameserver:
    - https://1.12.12.12/dns-query
    - https://223.5.5.5/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 240.0.0.0/4
  nameserver-policy:
    'api-huacloud.net': ['https://223.5.5.5/dns-query','https://1.12.12.12/dns-query']
    'framagit.org': ['https://223.5.5.5/dns-query','https://1.12.12.12/dns-query']
    'geosite:cn': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:SpecialDirect': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:GameDownloadCN': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:WeChat': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:GoogleFCM': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'rule-set:Streaming': 'https://1.0.0.1/dns-query#国际媒体'
    'rule-set:Apple': ['https://1.12.12.12/dns-query','https://223.5.5.5/dns-query']
    'geosite:telegram': 'https://1.0.0.1/dns-query#Fallback'
    'rule-set:Steam': 'https://1.0.0.1/dns-query#全球加速'
    'rule-set:Google': 'https://1.0.0.1/dns-query#全球加速'
    'rule-set:Bing': 'https://1.0.0.1/dns-query#全球加速'
prproxy: &p
  type: url-test
  use:
    - ProxyURL
  url: 'http://www.gstatic.com/generate_204'
  interval: 300
  hidden: true
proxy-groups:
  - name: 全球加速
    type: select
    proxies:
      - Fallback
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 下载节点
      - 其它节点
      - DIRECT
  - name: 国际媒体
    type: select
    proxies:
      - 全球加速
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: 游戏下载
    type: select
    proxies:
      - DIRECT
      - 下载节点
      - 全球加速
      - 其它节点
  - name: 游戏加速
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 下载节点
      - 其它节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
  - name: Microsoft
    type: select
    proxies:
      - 全球加速
      - DIRECT
      - 其它节点
  - name: Apple
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 其它节点
  - name: OneDrive
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 下载节点
  - name: 其它节点
    type: select
    filter: '(?=.*())^((?!(Netea|香港|新加|狮城|日本|Exp|Tra|台湾|美国)).)*$'
    use:
      - ProxyURL
  - name: Fallback
    type: fallback
    proxies:
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    hidden: true
  - name: 下载节点
    filter: '实验'
    <<: *p
  - name: 香港节点
    filter: '港|HK|(?i)Hong'
    <<: *p
  - name: 台湾节点
    filter: '台|TW|(?i)Taiwan'
    <<: *p
  - name: 日本节点
    filter: '日|JP|(?i)Japan'
    <<: *p
  - name: 新加坡节点
    filter: '新加|狮|獅|SG|(?i)Singapore'
    <<: *p
  - name: 美国节点 
    filter: '美|US|(?i)States|American'
    <<: *p
rule-providers:
  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: 'https://framagit.org/Locks7895/proxyrules/-/raw/main/Streaming.yaml'
    interval: 86400
  GoogleFCM:
    type: http
    behavior: classical
    path: ./rule_provider/GoogleFCM.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml'
    interval: 86400
  Google:
    type: http
    behavior: classical
    path: ./rule_provider/Google.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Google.yaml'
    interval: 86400
  Apple:
    type: http
    behavior: classical
    path: ./rule_provider/Apple.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml'
    interval: 86400
  Microsoft:
    type: http
    behavior: classical
    path: ./rule_provider/Microsoft.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml'
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    path: ./rule_provider/OneDrive.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml'
    interval: 86400
  Bing:
    type: http
    behavior: classical
    path: ./rule_provider/Bing.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml'
    interval: 86400
  GameDownload:
    type: http
    behavior: classical
    path: ./rule_provider/GameDownload.yaml
    url: 'https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GameDownload.yaml'
    interval: 86400
  GameDownloadCN:
    type: http
    behavior: classical
    path: ./rule_provider/GameDownloadCN.yaml
    url: 'https://framagit.org/Locks7895/proxyrules/-/raw/main/GameDownloadCN.yaml'
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: ./rule_provider/Game.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Game/Game.yaml'
    interval: 86400
  WeChat:
    type: http
    behavior: classical
    path: ./rule_provider/WeChat.yaml
    url: 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/WeChat/WeChat.yaml'
    interval: 86400
  Steam:
    type: http
    behavior: classical
    path: ./rule_provider/Steam.yaml
    url: 'https://framagit.org/Locks7895/proxyrules/-/raw/main/Steam.yaml'
    interval: 86400
  HTTPDNS:
    type: http
    behavior: classical
    path: ./rule_provider/HTTPDNS.yaml
    url: 'https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BlockHttpDNS/BlockHttpDNS.yaml'
    interval: 86400
  SpecialDirect:
    type: http
    behavior: classical
    path: ./rule_provider/SpecialDirect.yaml
    url: 'https://framagit.org/Locks7895/proxyrules/-/raw/main/SpecialDirect.yaml'
    interval: 86400
  Fakeip-Filter:
    type: http
    behavior: classical
    path: ./rule_provider/Fakeip-Filter.yaml
    url: 'https://framagit.org/Locks7895/proxyrules/-/raw/main/Fakeip-Filter.yaml'
    interval: 86400
  LAN:
    type: http
    behavior: classical
    path: ./rule_provider/Lan.yaml
    url: 'https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Lan/Lan.yaml'
    interval: 86400
rules:
  - SRC-PORT,31287,DIRECT
  - RULE-SET,LAN,DIRECT,no-resolve
  - DOMAIN-SUFFIX,framagit.org,DIRECT
  - DOMAIN,api-huacloud.net,DIRECT
  - RULE-SET,SpecialDirect,DIRECT
  - RULE-SET,Streaming,国际媒体
  - RULE-SET,GoogleFCM,DIRECT
  - GEOIP,telegram,Fallback,no-resolve
  - GEOSITE,telegram,Fallback
  - RULE-SET,Steam,全球加速
  - RULE-SET,OneDrive,OneDrive
  - RULE-SET,Bing,全球加速
  - RULE-SET,Microsoft,Microsoft
  - RULE-SET,Apple,Apple
  - RULE-SET,Google,全球加速
  - RULE-SET,GameDownloadCN,DIRECT
  - DOMAIN-SUFFIX,recaptcha.net,全球加速
  - RULE-SET,GameDownload,游戏下载
  - RULE-SET,Game,游戏加速,no-resolve
  - RULE-SET,HTTPDNS,REJECT
  - RULE-SET,WeChat,DIRECT,no-resolve
  - GEOSITE,gfw,全球加速
  - GEOSITE,cn,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,全球加速