geodata-mode: true 
geo-auto-update: true
geo-update-interval: 168
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-only-cn-private.mmdb"
tun:
  enable: true
  stack: system
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53
    - tcp://any:53
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  default-nameserver:
    - tcp://119.29.29.29:53
  nameserver-policy:
    'geosite:cn': 'tls://1.12.12.12:853'
    'mtalk.google.com': 'tls://1.12.12.12:853'
    'alt1-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt2-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt3-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt4-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt5-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt6-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt7-mtalk.google.com': 'tls://1.12.12.12:853'
    'alt8-mtalk.google.com': 'tls://1.12.12.12:853'
    'geosite:geolocation-!cn': 'tls://1.0.0.1:853#全球加速'
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.direct'
    - 'cable.auth.com'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - 'network-test.debian.org'
    - 'detectportal.firefox.com'
    - 'resolver1.opendns.com'
    - '*.srv.nintendo.net'
    - '*.stun.playstation.net'
    - 'xbox.*.microsoft.com'
    - '*.xboxlive.com'
    - 'stun.*'
    - 'global.turn.twilio.com'
    - 'global.stun.twilio.com'
    - 'app.yinxiang.com'
    - 'injections.adguard.org'
    - 'local.adguard.org'
    - 'cable.auth.com'
    - 'localhost.*.qq.com'
    - 'localhost.*.weixin.qq.com'
    - '*.logon.battlenet.com.cn'
    - '*.logon.battle.net'
    - '*.blzstatic.cn'
    - '+.music.163.com'
    - '*.126.net'
    - 'musicapi.taihe.com'
    - 'music.taihe.com'
    - 'songsearch.kugou.com'
    - 'trackercdn.kugou.com'
    - '*.kuwo.cn'
    - 'api-jooxtt.sanook.com'
    - 'api.joox.com'
    - 'joox.com'
    - '+.y.qq.com'
    - 'streamoc.music.tc.qq.com'
    - 'mobileoc.music.tc.qq.com'
    - 'isure.stream.qqmusic.qq.com'
    - 'dl.stream.qqmusic.qq.com'
    - 'aqqmusic.tc.qq.com'
    - 'amobile.music.tc.qq.com'
    - '*.xiami.com'
    - '*.music.migu.cn'
    - 'music.migu.cn'
    - 'proxy.golang.org'
    - '*.mcdn.bilivideo.cn'
    - '*.cmpassport.com'
    - 'id6.me'
    - 'open.e.189.cn'
    - 'mdn.open.wo.cn'
    - 'opencloud.wostore.cn'
    - 'auth.wosms.cn'
    - '*.jegotrip.com.cn'
    - '*.icitymobile.mobi'
    - '*.pingan.com.cn'
    - '*.cmbchina.com'
    - '+.pool.ntp.org'
    - 'ntp.*.com'
    - 'time.*.com'
    - 'ntp?.*.com'
    - 'time?.*.com'
    - 'time.*.gov'
    - 'time.*.edu.cn'
    - '*.ntp.org.cn'
    - 'PDC._msDCS.*.*'
    - 'DC._msDCS.*.*'
    - 'GC._msDCS.*.*'
    - '*.doh.pub'
    - '*.dot.pub'
    - '+.dns.google'
    - 'engage.nanocat.me'
    - 'alt1-mtalk.google.com'
    - 'alt2-mtalk.google.com'
    - 'alt3-mtalk.google.com'
    - 'alt4-mtalk.google.com'
    - 'alt5-mtalk.google.com'
    - 'alt6-mtalk.google.com'
    - 'alt7-mtalk.google.com'
    - 'alt8-mtalk.google.com'
    - 'mtalk.google.com'
  nameserver:
    - tls://1.12.12.12:853
  fallback:
    - 'tls://1.0.0.1:853#全球加速'
  proxy-server-nameserver:
    - tls://1.12.12.12:853
  fallback-filter:
    geoip: true
    geoip-code: cn
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 240.0.0.0/4
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.githubusercontent.com'
      - '+.googlevideo.com'
      - '+.msftconnecttest.com'
      - '+.msftncsi.com'
proxy-providers:
  Nice:
    type: http
    url: "此处填入订阅链接"
    interval: 86400
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  HK:
    filter: 港|HK|(?i)Hong
    type: file
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  TW:
    filter: 台|TW|(?i)Taiwan
    type: file
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  SG:
    filter: 新|狮|獅|SG|(?i)Singapore
    type: file
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  JP:
    filter: 日|JP|(?i)Japan
    type: file
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  US:
    filter: 美|US|(?i)States|American
    type: file
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  SP:
    filter: "(?=.*())^((?!(Netea|香港|新加|狮城|日本|Exp|Tra|台湾|美国)).)*$"
    type: file
    path: ./Nice.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
proxy-groups:
  - name: 全球加速
    type: select
    proxies:
      - Fallback
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
      - DIRECT
  - name: 国际媒体
    type: select
    proxies:
      - 全球加速
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: 游戏加速
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 其它节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
  - name: Telegram
    type: select
    proxies:
      - Fallback
      - 全球加速
  - name: Microsoft
    type: select
    proxies:
      - 全球加速
      - DIRECT
      - 其它节点
  - name: OneDrive
    type: select
    proxies:
      - DIRECT
      - 全球加速
  - name: 香港节点
    type: url-test
    use:
      - HK
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 台湾节点
    type: url-test
    use:
      - TW
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 日本节点
    type: url-test
    use:
      - JP
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 新加坡节点
    type: url-test
    use:
      - SG
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 美国节点
    type: url-test
    use:
      - US
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: Fallback
    type: fallback
    proxies:
      - 新加坡节点
      - 香港节点     
      - 日本节点
      - 台湾节点
      - 美国节点
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 其它节点
    type: select
    use:
      - SP
    url: "http://cp.cloudflare.com/"
    interval: 600
rule-providers:
  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Streaming.yaml
    interval: 86400
  GoogleFCM:
    type: http
    behavior: classical
    path: ./rule_provider/GoogleFCM.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: ./rule_provider/Game.yaml
    url: https://raw.githubusercontent.com/Toyro7356/ProxyConfig-Clash.meta/release/Rules/Game.yaml
    interval: 86400
rules:
  - IP-CIDR,1.12.12.12/32,DIRECT,no-resolve
  - IP-CIDR,120.53.53.53/32,DIRECT,no-resolve
  - IP-CIDR,119.29.29.29/32,DIRECT,no-resolve
  - DOMAIN,relay.firefox.com,台湾节点,no-resolve
  - RULE-SET,GoogleFCM,DIRECT,no-resolve
  - GEOIP,google,全球加速,no-resolve
  - GEOSITE,google,全球加速,no-resolve
  - GEOSITE,nvidia,全球加速,no-resolve
  - GEOSITE,category-games@cn,DIRECT,no-resolve
  - RULE-SET,Game,全球加速,no-resolve
  - GEOSITE,category-games,游戏加速,no-resolve
  - GEOIP,telegram,Telegram,no-resolve
  - GEOSITE,telegram,Telegram,no-resolve
  - GEOSITE,bahamut,台湾节点,no-resolve
  - GEOSITE,onedrive,OneDrive,no-resolve
  - GEOSITE,Bing,全球加速,no-resolve
  - GEOSITE,Microsoft,Microsoft,no-resolve
  - RULE-SET,Streaming,国际媒体,no-resolve
  - GEOSITE,cn,DIRECT,no-resolve
  - GEOSITE,gfw,全球加速,no-resolve
  - GEOSITE,Apple,DIRECT
  - GEOIP,cn,DIRECT
  - MATCH,全球加速