geodata-mode: true
geo-auto-update: true
geo-update-interval: 168
geox-url:
  geoip: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://testingcf.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/Country-only-cn-private.mmdb"
profile:
  store-selected: true
  store-fake-ip: true
tun:
  enable: true
  stack: system
  device: meta
  dns-hijack:
    - any:53
    - tcp://any:53
sniffer:
  enable: true
  force-dns-mapping: false
  parse-pure-ip: false
  override-destination: false
  sniff:
    QUIC:
      ports: [443]
    TLS:
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
dns:
  enable: true
  listen: 0.0.0.0:53
  ipv6: false
  enhanced-mode: redir-host
  default-nameserver:
    - tcp://119.29.29.29:53
  nameserver-policy:
    "geosite:Bing": "tls://1.0.0.1:853#全球加速"
    "geosite:bahamut": "tls://8.8.8.8:853#国际媒体"
    "mtalk.google.com": "tls://1.12.12.12:853"
    "alt1-mtalk.google.com": "tls://1.12.12.12:853"
    "alt2-mtalk.google.com": "tls://1.12.12.12:853"
    "alt3-mtalk.google.com": "tls://1.12.12.12:853"
    "alt4-mtalk.google.com": "tls://1.12.12.12:853"
    "alt5-mtalk.google.com": "tls://1.12.12.12:853"
    "alt6-mtalk.google.com": "tls://1.12.12.12:853"
    "alt7-mtalk.google.com": "tls://1.12.12.12:853"
    "alt8-mtalk.google.com": "tls://1.12.12.12:853"
    "geosite:geolocation-!cn": "tls://1.0.0.1:853#全球加速"
    "geosite:cn": "tls://1.12.12.12:853"
  nameserver:
    - tls://1.12.12.12:853
  fallback:
    - "tls://1.0.0.1:853#全球加速"
  proxy-server-nameserver:
    - tls://1.12.12.12:853
  fallback-filter:
    geoip: true
    geoip-code: cn
    ipcidr:
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 240.0.0.0/4
    domain:
      - "+.google.com"
      - "+.facebook.com"
      - "+.youtube.com"
      - "+.githubusercontent.com"
      - "+.googlevideo.com"
      - "+.msftconnecttest.com"
      - "+.msftncsi.com"
      - "+.bing.com"
      - "+.bing.cn"
proxy-providers:
  VPN:
    type: http
    url: "https://订阅链接"
    interval: 86400
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  HK:
    filter: 港|HK|(?i)Hong
    type: file
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  TW:
    filter: 台|TW|(?i)Taiwan
    type: file
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  SG:
    filter: 新|狮|獅|SG|(?i)Singapore
    type: file
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  JP:
    filter: 日|JP|(?i)Japan
    type: file
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  US:
    filter: 美|US|(?i)States|American
    type: file
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
  SP:
    filter: "(?=.*())^((?!(Netea|香港|新加|狮城|日本|Exp|Tra|台湾|美国)).)*$"
    type: file
    path: ./VPN.yaml
    health-check:
      enable: true
      interval: 1200
      url: http://cp.cloudflare.com/
proxy-groups:
  - name: 全球加速
    type: select
    proxies:
      - Fallback
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
      - DIRECT
  - name: 国际媒体
    type: select
    proxies:
      - 全球加速
      - 香港节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
      - 其它节点
  - name: 游戏加速
    type: select
    proxies:
      - DIRECT
      - 全球加速
      - 其它节点
      - 台湾节点
      - 日本节点
      - 新加坡节点
      - 美国节点
  - name: Microsoft
    type: select
    proxies:
      - 全球加速
      - DIRECT
      - 其它节点
  - name: OneDrive
    type: select
    proxies:
      - DIRECT
      - 全球加速
  - name: 香港节点
    type: load-balance
    use:
      - HK
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 台湾节点
    type: load-balance
    use:
      - TW
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 日本节点
    type: load-balance
    use:
      - JP
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 新加坡节点
    type: load-balance
    use:
      - SG
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 美国节点
    type: url-test
    use:
      - US
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: Fallback
    type: fallback
    proxies:
      - 新加坡节点
      - 日本节点
      - 台湾节点
      - 香港节点
      - 美国节点
    url: "http://cp.cloudflare.com/"
    interval: 600
  - name: 其它节点
    type: select
    use:
      - SP
    url: "http://cp.cloudflare.com/"
    interval: 600
rule-providers:
  Streaming:
    type: http
    behavior: classical
    path: ./rule_provider/Streaming.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
    interval: 86400
  GoogleFCM:
    type: http
    behavior: classical
    path: ./rule_provider/GoogleFCM.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleFCM/GoogleFCM.yaml
    interval: 86400
  Game:
    type: http
    behavior: classical
    path: ./rule_provider/Game.yaml
    url: https://raw.githubusercontent.com/Toyro7356/ProxyConfig-Clash.meta/main/Rules/Game.yaml
    interval: 86400
rules:
  - IP-CIDR,1.12.12.12/32,DIRECT,no-resolve
  - IP-CIDR,120.53.53.53/32,DIRECT,no-resolve
  - IP-CIDR,119.29.29.29/32,DIRECT,no-resolve
  - RULE-SET,GoogleFCM,DIRECT,no-resolve
  - GEOIP,google,全球加速,no-resolve
  - GEOSITE,google,全球加速,no-resolve
  - GEOSITE,nvidia,全球加速,no-resolve
  - GEOSITE,category-games@cn,DIRECT,no-resolve
  - RULE-SET,Game,全球加速,no-resolve
  - GEOSITE,category-games,游戏加速,no-resolve
  - GEOIP,telegram,Fallback,no-resolve
  - GEOSITE,telegram,Fallback,no-resolve
  - GEOSITE,bahamut,台湾节点,no-resolve
  - GEOSITE,onedrive,OneDrive,no-resolve
  - GEOSITE,Bing,全球加速,no-resolve
  - GEOSITE,Microsoft,Microsoft,no-resolve
  - RULE-SET,Streaming,国际媒体,no-resolve
  - GEOSITE,gfw,全球加速,no-resolve
  - GEOSITE,cn,DIRECT,no-resolve
  - GEOIP,cn,DIRECT
  - MATCH,全球加速